### ISSUE TITLE
How to avoid superfluous commas when using \<mfenced\>

### ISSUE THREAD

**Issue by TimArborealis** [nlbdev/mathml-guidelines#7]
We have seen many errors like the following where the markup
![bild](https://github.com/nlbdev/mathml-guidelines/assets/143188129/f8709002-1cf5-47f2-8b2b-5a0277b52211)
results in superfluous commas, like so:
![bild](https://github.com/nlbdev/mathml-guidelines/assets/143188129/76519ec2-1c96-4fe6-b941-f9b2f0d1a949)

Here the commas need not be marked up but will be rendered automatically between \<mi\> elements. Maybe we can clarify this in the section on \<mfenced\>. 

In other cases, sometimes the attribute separators might need to be set to separators=""?

**Comment by josteinaj** [comment]
@GauteR: Denne saken var ikke tilordnet noen. Setter den til deg siden du er eier av dette repoet.

_(dette er en automatisk melding)_

**Comment by samimaattaCelia** [comment]
In this case you wouldn't need the `<mo>` elements for the comma, since `<mfenced>` would render them automatically as per [MathML 3 3.3.8](https://www.w3.org/TR/MathML3/chapter3.html#presm.mfenced) and [MathML 4 3.3.8 ](https://www.w3.org/TR/mathml4/#presm_mfenced_att_ex).

## Sensible `<mfenced>` use cases

It's not useful for a+b, but it would be useful for {1,2,3,4,5,...,n}, so that you don't have to write really verbose markup. Compare:

**Without `<mfenced>`:**
```html
<mo>{</mo>
<mn>1</mn>
<mo>,</mo>
<mn>2</mn>
<mo>,</mo>
<mn>3</mn>
<mo>,</mo>
<mn>4</mn>
<mo>,</mo>
<mn>5</mn>
<mo>,</mo>
<mi>[ellipses]</mi>
<mo>,</mo>
<mi>n</mi>
<mo>}</mo>
```

**With `<mfenced>`:**
```html
<mfenced open="{" close="}">
  <mn>1</mn>
  <mn>2</mn>
  <mn>3</mn>
  <mn>4</mn>
  <mn>5</mn>
  <mi>[ellipse]</mi>
  <mi>n</mi>
</mfenced>
```

I think it's up for debate if this is really that much more useful. Maybe there are other use cases it's good for.

## Should we use it?

I say we should **not use it**. Why?
- It's not part of MathML Core
- the implementation support might be spotty
- it's confusing to the suppliers (as per this issue).

Relates to issue #9, where I propose not using it in the future.

**Comment by samimaattaCelia** [comment]
To answer your question, you can get rid of the separators by using the attribute `separators=""`: `<mfenced separators="">`.

**Comment by samimaattaCelia** [comment]
Closing this issue as <mfenced> is deprecated and shouldn't be used.
