### ISSUE TITLE
Question: should \<mfenced\> be discontinued?

### ISSUE THREAD

**Issue by TimArborealis** [nlbdev/mathml-guidelines#9]
What are the pros and cons of using \<mfenced\> vs \<mo\>(<\/mo\> etc.? It's never been clear to me why we should use one and not the other.

**Comment by samimaattaCelia** [comment]
To me it seems that you could use `<mfenced>`, but it's not covered by MathML Core ([MathML 4 3.3.8.1](https://w3c.github.io/mathml/#presm_mfenced_desc)), so support for it might not be optimal in the future. I also don't know what the support is now.

For some reason on [MDN Web Docs say that it's deprecated](https://developer.mozilla.org/en-US/docs/Web/MathML/Element/mfenced) even though it's mentioned in MathML 4 ([3.3.8.1](https://w3c.github.io/mathml/#presm_mfenced_desc)) and it's explained pretty extensibly. [The deprecation mention was apparently included by a MathML Core contributor, Fred Wang (GitHub)](https://github.com/mdn/content/commit/0fb5d5d5579d459f58ab52d0e6e94fc4634a9fe0).

To me it seems really complicated to use, since it doesn't apply for every "fenced expressions" (as per [MathML 4 3.3.8.2](https://w3c.github.io/mathml/#presm_mfenced_att)). Also the [examples (MathML 4 3.3.8.3)](https://w3c.github.io/mathml/#presm_mfenced_att_ex) highlight some weird mark up that you have to remember to do if you use it.

I would say we are better off **not using it**, and focusing on correct mark up with `<mo>`.

**Comment by samimaattaCelia** [comment]
Closing this issue as `<mfenced>` is deprecated and shouldn't be used.

**Comment by TimArborealis** [comment]
Reopening this issue to ask if we should explicitly mention in the guidelines that mfenced has been discontinued. Right now they frequently use it.

**Comment by AndersEkl** [comment]
We can add a comment about it in the section covering the `<mo>` element.

**Comment by AndersEkl** [comment]
I have added this text now.

**Comment by AndersEkl** [comment]
Closing this issue again, as it is now explicitly mentioned.
